### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by astoilkov** [plrenaudin/goto-last-edit#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.9.5
**Thrown From**: [goto-last-edit](https://github.com/plrenaudin/goto-last-edit) package, v0.2.1
### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At /Users/astoilkov/.atom/packages/goto-last-edit/lib/goto-last-edit.coffee:53

TypeError: Cannot read property 'row' of undefined
  at Object.module.exports.run (/Users/astoilkov/.atom/packages/goto-last-edit/lib/goto-last-edit.coffee:53:50)
  at atom-workspace.subscriptions.add.atom.commands.add.goto-last-edit:run (/Users/astoilkov/.atom/packages/goto-last-edit/lib/goto-last-edit.coffee:18:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:23 core:move-right (atom-text-editor.editor.is-focused)
     -0:21.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:21.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:move-to-top (atom-text-editor.editor.is-focused)
 10x -0:16.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:14.7.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:14.3.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:13.2.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:12.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.2.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:07.5.0 goto-last-edit:run (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:04.0 goto-last-edit:run (atom-text-editor.editor.is-focused)
     -0:01.2.0 pane:show-next-item (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
goto-last-edit, v0.2.1
linter, v1.1.0
react, v0.12.2

# Dev
No dev packages
```

**Comment by plrenaudin** [comment]
Would it be possible to have more details about the steps to reproduce this bug?
Looking at the list of command alone doesn't give me much unfortunately.

**Comment by astoilkov** [comment]
Sorry. I didn't understand the scenario either. Atom just automatically created a popup with the error and let me post it here.

**Comment by jeancroy** [comment]
At [line 44](https://github.com/plrenaudin/goto-last-edit/blob/master/lib/goto-last-edit.coffee#L44) you guard against case where history exist but have no position.

The error occurs at [line 53/54](https://github.com/plrenaudin/goto-last-edit/blob/master/lib/goto-last-edit.coffee#L53) where you try to get row/cols of the position. And it looks sometime that position does not exist (thus you cannot get `position.row`). 

Because the [editor exist](https://github.com/plrenaudin/goto-last-edit/blob/master/lib/goto-last-edit.coffee#L51) one thing you could do is switch tab but don't move cursor.

**Comment by plrenaudin** [comment]
Thanks @jeancroy , I thought about pushing the last edit position in history only if it's valid.
But before that I wanted to understand what is causing this in order to write the failing test before fixing this. I guess I will just have to skip the test =(

Edit: It seems to happen when there is split panes particularly... And for some reason the last edit position get lost.

**Comment by plrenaudin** [comment]
Fixed but not properly reproduced so no real test added
